secretsprovider: gcpkms://projects/spigell-resume-production/locations/global/keyRings/pulumi-runner-keyring/cryptoKeys/pulumi-runner-key
encryptedkey: CiQAwI7Uw2DS8Bf4NiF3ajugXdBw62GlLvRVtJUlmbeFuKmT2AISSQAcq2Fz4pDcC/wESlXxGBPdbNs2SjmGC1cTfTEz6OT+mZ9SNAv4LH71eXqJYF/XxtarYyYeOyZ7FNY7mU6X/QTIL3u1T6Rjcbk=
config:
  gcp:project: spigell-resume-production
  gcp:region: us-central1
  my-cloud-resume:resume:
    gcp:
      domains:
        - config:
            record: sergeichukh.cloud
            token:
              secure: v1:Gyd+T6fP8YAnkdYy:A5KTY3/OO6CxoxP8RVXgUgKSC4+hkAPjnSj5ICO1J83yXSCDERSZTATilKhuPAmHvSlOemf6XNk=
            zoneId: 42aa355ee597a9aa3ea2f3ebbc1f6190
          type: cloudflare
      gcs:
        proxy:
          image: us-central1-docker.pkg.dev/spigell-resume-production/resume-images/gcp-proxy:2bee0b
      loadbalancers:
        config:
          traefik:
            basicAuth: false
        primary: kubernetes/traefik
