secretsprovider: gcpkms://projects/spigell-resume-dev/locations/global/keyRings/pulumi-runner-keyring/cryptoKeys/pulumi-runner-key
encryptedkey: CiQAzKoSuPfrCwtc4FQcHDzCctCOqCsRzqSPSePy2txofBjhpFUSSQCa0TfO1qLdz9v8LfQ5Od71xFwQRjGjzuk5ty7r1Nalb3A9YpSyF9C/0r5EayjZMLfTXC2mYHrwKOS53QSPAbkJ+mribGvaOnI=
config:
  gcp:project: spigell-resume-dev
  gcp:region: us-central1
  my-cloud-resume:resume:
    gcp:
      domains:
        - config:
            record: dev.sergeichukh.cloud
            zoneId: 42aa355ee597a9aa3ea2f3ebbc1f6190
            token:
              secure: v1:iqMSmJZ58DZ0kqsz:f9aZwty0K0nuTakdalFaVnfs5ODYXcIOgub5BSOJcEYbitcuS/ftRIAWFY8cBFdfPaFSt2/0UFs=
          type: cloudflare
      gcs:
        proxy:
          image: us-central1-docker.pkg.dev/spigell-resume-production/resume-images/gcp-proxy:2bee0b
      loadbalancers:
        config:
          traefik:
            basicAuth: true
        primary: kubernetes/traefik
