secretsprovider: gcpkms://projects/spigell-resume-dev/locations/global/keyRings/pulumi-runner-keyring/cryptoKeys/pulumi-runner-key
encryptedkey: CiQAzKoSuPfrCwtc4FQcHDzCctCOqCsRzqSPSePy2txofBjhpFUSSQCa0TfO1qLdz9v8LfQ5Od71xFwQRjGjzuk5ty7r1Nalb3A9YpSyF9C/0r5EayjZMLfTXC2mYHrwKOS53QSPAbkJ+mribGvaOnI=
config:
  gcp:project: spigell-resume-dev
  gcp:region: us-central1
  my-cloud-resume:resume:
    gcp:
      domains:
      - dev.sergeichukh.cloud
      - test.sergeichukh.cloud
      gcs:
        proxy:
          image: us-central1-docker.pkg.dev/spigell-resume-production/resume-images/gcp-proxy:2bee0b
      loadbalancers:
        backup: gcp/classic
        primary: kubernetes/traefik
        config:
          traefik:
            basicAuth: true
