name: Build html and pdf
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and save html and pdf
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 6
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Check connectivity to Simple Icons CDN
        run: curl -I https://cdn.simpleicons.org/telegram
      - run: yarn build:pdf && yarn build:website-resume
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ steps.short-sha.outputs.sha }}
          if-no-files-found: error
          path: |
            resume/artifacts/*
