name: Destroy a environment via pulumi
on:
  delete:
    branches:
      - dev

defaults:
  run:
    shell: bash
    working-directory: infra

jobs:
  destroy:
    name: Destroy
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.pulumi.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: yarn install
        working-directory: infra
      - uses: pulumi/actions@v4
        id: pulumi
        with:
          command: destroy
          stack-name: ${{ github.ref_name }}
          work-dir: infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
