name: Run deploy via Pulumi
on:
  push:
    branches:
      - production
      - dev
    paths:
      - 'infra/**'
      - 'frontend/**'

defaults:
  run:
    shell: bash
    working-directory: infra

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_DEPLOYER_CREDENTIALS }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'main'
          location: 'us-central1-c'
      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Install pulumi cli
        uses: pulumi/actions@v4
      - name: Run pulumi preview via automation API
        run: npx ts-node ./automations.ts
        env:
          DRY_RUN: true
          STACK: ${{ github.ref_name }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  up:
    needs:
      - preview
    name: Deploy
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.get-env-url.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_DEPLOYER_CREDENTIALS }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'main'
          location: 'us-central1-c'
      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: yarn install
      - name: Install pulumi cli
        uses: pulumi/actions@v4
      - name: Run pulumi preview via automation API
        run: npx ts-node ./automations.ts
        env:
          STACK: ${{ github.ref_name }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Get env url from pulumi output
        id: get-env-url
        run: echo URL=$(pulumi stack ouputs url) >> $GITHUB_OUTPUT
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
