name: Run deploy via Pulumi
on:
  push:
    branches:
      - production
      - dev
    paths:
      - 'infra/**'
      - 'frontend/**'

defaults:
  run:
    shell: bash
    working-directory: infra

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_DEPLOYER_CREDENTIALS }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'main'
          location: 'us-central1-c'
      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: yarn install
      - uses: pulumi/actions@v4
        id: pulumi
        with:
          command: preview
          stack-name: ${{ github.ref_name }}
          diff: true
          work-dir: infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  up:
    needs:
      - preview
    name: Deploy
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.pulumi.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_DEPLOYER_CREDENTIALS }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'main'
          location: 'us-central1-c'
      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependencies
        run: yarn install
        working-directory: infra
      - uses: pulumi/actions@v4
        id: pulumi
        with:
          command: up
          stack-name: ${{ github.ref_name }}
          work-dir: infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
